<?php

namespace ORG\BirdBundle\Repository;
use ORG\BirdBundle\Model\Filter\FilterInterface;
use ORG\BirdBundle\Model\OrderBy\OrderByInterface;

/**
 * CycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CycleRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Retourne un Objet QueryBuilder filtré et trié sur base des objets passés en parametre
     * @param FilterInterface $filter
     * @param OrderByInterface $orderBy
     * @return mixed
     */
    public function getQueryBuilderFiltered(FilterInterface $filter, OrderByInterface $orderBy)
    {
        return $orderBy->getQueryBuilder($filter->getQueryBuilder($this->createQueryBuilder('c')->leftJoin('c.authors','a')->addSelect('a')));
    }

    /**
     * Retourne un objet QueryBuilder trié sur base de l'objet OrderInterface passé en parametre
     * @param OrderByInterface $orderBy
     * @return mixed
     */
    public function getQueryBuilderOrderBy(OrderByInterface $orderBy)
    {
        return $orderBy->getQueryBuilder($this->createQueryBuilder('c'));
    }
}
