<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendValuesBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendValuesBookRepository extends \Doctrine\ORM\EntityRepository
{
}
