<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendValuesCycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendValuesCycleRepository extends \Doctrine\ORM\EntityRepository
{
}
