<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendFieldsAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendFieldsAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
