<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendFieldsCycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendFieldsCycleRepository extends \Doctrine\ORM\EntityRepository
{
}
