<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendFieldsBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendFieldsBookRepository extends \Doctrine\ORM\EntityRepository
{
}
