<?php

namespace ORG\BirdBundle\Repository;

/**
 * ExtendValuesAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtendValuesAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
