<?php

namespace ORG\BirdBundle\Repository;

/**
 * LinkFieldsCycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkFieldsCycleRepository extends \Doctrine\ORM\EntityRepository
{
}
