<?php

namespace ORG\BirdBundle\Repository;

/**
 * LinkFieldsBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkFieldsBookRepository extends \Doctrine\ORM\EntityRepository
{
}
