<?php

namespace ORG\BirdBundle\Repository;

/**
 * LinkFieldsAuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkFieldsAuthorRepository extends \Doctrine\ORM\EntityRepository
{
}
