<?php

namespace Proxies\__CG__\ORG\BirdBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ExtendValuesBook extends \ORG\BirdBundle\Entity\ExtendValuesBook implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'id', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'stringvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'numbervalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'decimalvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'longtextvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'datevalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'booleanvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'emailvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'urlvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'choicevalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'createdate', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'linkExtendBook'];
        }

        return ['__isInitialized__', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'id', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'stringvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'numbervalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'decimalvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'longtextvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'datevalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'booleanvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'emailvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'urlvalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'choicevalue', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'createdate', '' . "\0" . 'ORG\\BirdBundle\\Entity\\ExtendValuesBook' . "\0" . 'linkExtendBook'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ExtendValuesBook $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setStringvalue($stringvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStringvalue', [$stringvalue]);

        return parent::setStringvalue($stringvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getStringvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStringvalue', []);

        return parent::getStringvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumbervalue($numbervalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumbervalue', [$numbervalue]);

        return parent::setNumbervalue($numbervalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumbervalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumbervalue', []);

        return parent::getNumbervalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecimalvalue($decimalvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecimalvalue', [$decimalvalue]);

        return parent::setDecimalvalue($decimalvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecimalvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecimalvalue', []);

        return parent::getDecimalvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongtextvalue($longtextvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongtextvalue', [$longtextvalue]);

        return parent::setLongtextvalue($longtextvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongtextvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongtextvalue', []);

        return parent::getLongtextvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatevalue($datevalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatevalue', [$datevalue]);

        return parent::setDatevalue($datevalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatevalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatevalue', []);

        return parent::getDatevalue();
    }

    /**
     * {@inheritDoc}
     */
    public function getBooleanvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBooleanvalue', []);

        return parent::getBooleanvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setBooleanvalue($booleanvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBooleanvalue', [$booleanvalue]);

        return parent::setBooleanvalue($booleanvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailvalue', []);

        return parent::getEmailvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailvalue($emailvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailvalue', [$emailvalue]);

        return parent::setEmailvalue($emailvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlvalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlvalue', []);

        return parent::getUrlvalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlvalue($urlvalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlvalue', [$urlvalue]);

        return parent::setUrlvalue($urlvalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getChoicevalue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChoicevalue', []);

        return parent::getChoicevalue();
    }

    /**
     * {@inheritDoc}
     */
    public function setChoicevalue($choicevalue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChoicevalue', [$choicevalue]);

        return parent::setChoicevalue($choicevalue);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedate', []);

        return parent::getCreatedate();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedate(\DateTime $createdate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedate', [$createdate]);

        return parent::setCreatedate($createdate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLinkExtendBook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLinkExtendBook', []);

        return parent::getLinkExtendBook();
    }

    /**
     * {@inheritDoc}
     */
    public function setLinkExtendBook($linkExtendBook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLinkExtendBook', [$linkExtendBook]);

        return parent::setLinkExtendBook($linkExtendBook);
    }

}
