<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.group.form.type' shared service.

return $this->services['fos_user.group.form.type'] = new \FOS\UserBundle\Form\Type\GroupFormType('ORG\\BirdBundle\\Entity\\Security\\Group');
