<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_user.group_manager' shared service.

return $this->services['fos_user.group_manager'] = new \FOS\UserBundle\Doctrine\GroupManager(${($_ = isset($this->services['fos_user.object_manager']) ? $this->services['fos_user.object_manager'] : $this->load(__DIR__.'/getFosUser_ObjectManagerService.php')) && false ?: '_'}, 'ORG\\BirdBundle\\Entity\\Security\\Group');
