<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (!class_exists(\ContainerHw2gx3z\appDevDebugProjectContainer::class, false)) {
    require __DIR__.'/ContainerHw2gx3z/appDevDebugProjectContainer.php';
}

if (!class_exists(appDevDebugProjectContainer::class, false)) {
    class_alias(\ContainerHw2gx3z\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHw2gx3z\appDevDebugProjectContainer();
